//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace SisPer.Aplicativo
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class ClockCardEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto ClockCardEntities usando la cadena de conexión encontrada en la sección 'ClockCardEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public ClockCardEntities() : base("name=ClockCardEntities", "ClockCardEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ClockCardEntities.
        /// </summary>
        public ClockCardEntities(string connectionString) : base(connectionString, "ClockCardEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ClockCardEntities.
        /// </summary>
        public ClockCardEntities(EntityConnection connection) : base(connection, "ClockCardEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<FICHADA> FICHADA
        {
            get
            {
                if ((_FICHADA == null))
                {
                    _FICHADA = base.CreateObjectSet<FICHADA>("FICHADA");
                }
                return _FICHADA;
            }
        }
        private ObjectSet<FICHADA> _FICHADA;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet FICHADA. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToFICHADA(FICHADA fICHADA)
        {
            base.AddObject("FICHADA", fICHADA);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClockCardModel", Name="FICHADA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FICHADA : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto FICHADA.
        /// </summary>
        /// <param name="fIC_ID">Valor inicial de la propiedad FIC_ID.</param>
        /// <param name="fIC_TARJETA">Valor inicial de la propiedad FIC_TARJETA.</param>
        /// <param name="fIC_FECHA">Valor inicial de la propiedad FIC_FECHA.</param>
        /// <param name="fIC_HORA">Valor inicial de la propiedad FIC_HORA.</param>
        /// <param name="fIC_ENTSAL">Valor inicial de la propiedad FIC_ENTSAL.</param>
        /// <param name="fIC_ORIGEN">Valor inicial de la propiedad FIC_ORIGEN.</param>
        public static FICHADA CreateFICHADA(global::System.Int32 fIC_ID, global::System.Int32 fIC_TARJETA, global::System.DateTime fIC_FECHA, global::System.String fIC_HORA, global::System.String fIC_ENTSAL, global::System.String fIC_ORIGEN)
        {
            FICHADA fICHADA = new FICHADA();
            fICHADA.FIC_ID = fIC_ID;
            fICHADA.FIC_TARJETA = fIC_TARJETA;
            fICHADA.FIC_FECHA = fIC_FECHA;
            fICHADA.FIC_HORA = fIC_HORA;
            fICHADA.FIC_ENTSAL = fIC_ENTSAL;
            fICHADA.FIC_ORIGEN = fIC_ORIGEN;
            return fICHADA;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FIC_ID
        {
            get
            {
                return _FIC_ID;
            }
            set
            {
                if (_FIC_ID != value)
                {
                    OnFIC_IDChanging(value);
                    ReportPropertyChanging("FIC_ID");
                    _FIC_ID = StructuralObject.SetValidValue(value, "FIC_ID");
                    ReportPropertyChanged("FIC_ID");
                    OnFIC_IDChanged();
                }
            }
        }
        private global::System.Int32 _FIC_ID;
        partial void OnFIC_IDChanging(global::System.Int32 value);
        partial void OnFIC_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LEG_LEGAJO
        {
            get
            {
                return _LEG_LEGAJO;
            }
            set
            {
                OnLEG_LEGAJOChanging(value);
                ReportPropertyChanging("LEG_LEGAJO");
                _LEG_LEGAJO = StructuralObject.SetValidValue(value, "LEG_LEGAJO");
                ReportPropertyChanged("LEG_LEGAJO");
                OnLEG_LEGAJOChanged();
            }
        }
        private Nullable<global::System.Int32> _LEG_LEGAJO;
        partial void OnLEG_LEGAJOChanging(Nullable<global::System.Int32> value);
        partial void OnLEG_LEGAJOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FIC_TARJETA
        {
            get
            {
                return _FIC_TARJETA;
            }
            set
            {
                OnFIC_TARJETAChanging(value);
                ReportPropertyChanging("FIC_TARJETA");
                _FIC_TARJETA = StructuralObject.SetValidValue(value, "FIC_TARJETA");
                ReportPropertyChanged("FIC_TARJETA");
                OnFIC_TARJETAChanged();
            }
        }
        private global::System.Int32 _FIC_TARJETA;
        partial void OnFIC_TARJETAChanging(global::System.Int32 value);
        partial void OnFIC_TARJETAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FIC_FECHA
        {
            get
            {
                return _FIC_FECHA;
            }
            set
            {
                OnFIC_FECHAChanging(value);
                ReportPropertyChanging("FIC_FECHA");
                _FIC_FECHA = StructuralObject.SetValidValue(value, "FIC_FECHA");
                ReportPropertyChanged("FIC_FECHA");
                OnFIC_FECHAChanged();
            }
        }
        private global::System.DateTime _FIC_FECHA;
        partial void OnFIC_FECHAChanging(global::System.DateTime value);
        partial void OnFIC_FECHAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FIC_HORA
        {
            get
            {
                return _FIC_HORA;
            }
            set
            {
                OnFIC_HORAChanging(value);
                ReportPropertyChanging("FIC_HORA");
                _FIC_HORA = StructuralObject.SetValidValue(value, false, "FIC_HORA");
                ReportPropertyChanged("FIC_HORA");
                OnFIC_HORAChanged();
            }
        }
        private global::System.String _FIC_HORA;
        partial void OnFIC_HORAChanging(global::System.String value);
        partial void OnFIC_HORAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FIC_ENTSAL
        {
            get
            {
                return _FIC_ENTSAL;
            }
            set
            {
                OnFIC_ENTSALChanging(value);
                ReportPropertyChanging("FIC_ENTSAL");
                _FIC_ENTSAL = StructuralObject.SetValidValue(value, false, "FIC_ENTSAL");
                ReportPropertyChanged("FIC_ENTSAL");
                OnFIC_ENTSALChanged();
            }
        }
        private global::System.String _FIC_ENTSAL;
        partial void OnFIC_ENTSALChanging(global::System.String value);
        partial void OnFIC_ENTSALChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FIC_RELOJ
        {
            get
            {
                return _FIC_RELOJ;
            }
            set
            {
                OnFIC_RELOJChanging(value);
                ReportPropertyChanging("FIC_RELOJ");
                _FIC_RELOJ = StructuralObject.SetValidValue(value, "FIC_RELOJ");
                ReportPropertyChanged("FIC_RELOJ");
                OnFIC_RELOJChanged();
            }
        }
        private Nullable<global::System.Int32> _FIC_RELOJ;
        partial void OnFIC_RELOJChanging(Nullable<global::System.Int32> value);
        partial void OnFIC_RELOJChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FIC_ORIGEN
        {
            get
            {
                return _FIC_ORIGEN;
            }
            set
            {
                OnFIC_ORIGENChanging(value);
                ReportPropertyChanging("FIC_ORIGEN");
                _FIC_ORIGEN = StructuralObject.SetValidValue(value, false, "FIC_ORIGEN");
                ReportPropertyChanged("FIC_ORIGEN");
                OnFIC_ORIGENChanged();
            }
        }
        private global::System.String _FIC_ORIGEN;
        partial void OnFIC_ORIGENChanging(global::System.String value);
        partial void OnFIC_ORIGENChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FIC_NOVEDAD
        {
            get
            {
                return _FIC_NOVEDAD;
            }
            set
            {
                OnFIC_NOVEDADChanging(value);
                ReportPropertyChanging("FIC_NOVEDAD");
                _FIC_NOVEDAD = StructuralObject.SetValidValue(value, "FIC_NOVEDAD");
                ReportPropertyChanged("FIC_NOVEDAD");
                OnFIC_NOVEDADChanged();
            }
        }
        private Nullable<global::System.Int32> _FIC_NOVEDAD;
        partial void OnFIC_NOVEDADChanging(Nullable<global::System.Int32> value);
        partial void OnFIC_NOVEDADChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FIC_EQUIPO
        {
            get
            {
                return _FIC_EQUIPO;
            }
            set
            {
                OnFIC_EQUIPOChanging(value);
                ReportPropertyChanging("FIC_EQUIPO");
                _FIC_EQUIPO = StructuralObject.SetValidValue(value, true, "FIC_EQUIPO");
                ReportPropertyChanged("FIC_EQUIPO");
                OnFIC_EQUIPOChanged();
            }
        }
        private global::System.String _FIC_EQUIPO;
        partial void OnFIC_EQUIPOChanging(global::System.String value);
        partial void OnFIC_EQUIPOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FIC_NOTAS
        {
            get
            {
                return _FIC_NOTAS;
            }
            set
            {
                OnFIC_NOTASChanging(value);
                ReportPropertyChanging("FIC_NOTAS");
                _FIC_NOTAS = StructuralObject.SetValidValue(value, true, "FIC_NOTAS");
                ReportPropertyChanged("FIC_NOTAS");
                OnFIC_NOTASChanged();
            }
        }
        private global::System.String _FIC_NOTAS;
        partial void OnFIC_NOTASChanging(global::System.String value);
        partial void OnFIC_NOTASChanged();

        #endregion

    }

    #endregion

}
