//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisPer.Aplicativo {
    
    
    public partial class Personal_Informe_AgentesPorArea {
        
        /// <summary>
        /// MenuPersonalJefe1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SisPer.Aplicativo.Menues.MenuPersonalJefe MenuPersonalJefe1;
        
        /// <summary>
        /// MenuPersonalAgente1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SisPer.Aplicativo.Menues.MenuPersonalAgente MenuPersonalAgente1;
        
        /// <summary>
        /// AgentesPorAreaUC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SisPer.Aplicativo.Reportes.AgentesPorAreaUC AgentesPorAreaUC;
    }
}
